setwd("/Users/ashwinsureshbabu/NCI/SEM 1/Statistics for Data Analytics")
dataset1<- read.csv("transformincome.csv", header=T, stringsAsFactors = T)
head(dataset1)

lmfit1<-lm(income~age+yrsed+edcat+yrsempl+creddebt+othdebt+default+jobsat+homeown+address+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~age+edcat+yrsempl+creddebt+othdebt+default+jobsat+homeown+address+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~edcat+yrsempl+creddebt+othdebt+default+jobsat+homeown+address+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~edcat+yrsempl+creddebt+othdebt+default+jobsat+homeown+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~yrsempl+creddebt+othdebt+default+jobsat+homeown+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~yrsempl+creddebt+othdebt+jobsat+homeown+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~yrsempl+creddebt+othdebt+jobsat+cars+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(income~yrsempl+creddebt+othdebt+jobsat+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

#Now the preceeding models are made after transformations are applied

setwd("/Users/ashwinsureshbabu/NCI/SEM 1/Statistics for Data Analytics")
dataset1<- read.csv("transformincome.csv", header=T, stringsAsFactors = T)
head(dataset1)

lmfit1<-lm(logofincome~yrsempl+creddebt+othdebt+jobsat+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(logofincome~logofyrsempl+creddebt+othdebt+jobsat+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(logofincome~yrsempl+logofcreddebt+othdebt+jobsat+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(logofincome~yrsempl+creddebt+othdebt+logofjobsat+carvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

lmfit1<-lm(logofincome~yrsempl+creddebt+othdebt+jobsat+logofcarvalue, data=dataset1)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)

#removing rows using cooks distance

cooksD <- cooks.distance(lmfit)
n <- nrow(dataset1)
plot(cooksD, main = "Cooks dictance for influential obs")
abline(h = 4/n, lty = 4, col = "red")
influential_obs <- as.numeric(names(cooksD)[(cooksD > (4/n))])
rm_outlier_cook <- dataset1[-influential_obs, ]
dim(rm_outlier_cook)
boxplot(rm_outlier_cook$logofincome)
cor(rm_outlier_cook)

lmfit1<-lm(logofincome~yrsempl+creddebt+othdebt+jobsat+logofcarvalue, data=rm_outlier_cook)
summary(lmfit1)
par(mfrow=c(2,2))
plot(lmfit1)
ncvTest(lmfit1)
AIC(lmfit1)
BIC(lmfit1)
